### ISSUE TITLE
Issue on computing MMADE and MMFDE

### ISSUE THREAD

**Issue by XiaoyuBIE1994** [Droliven/diverse_sampling#2]
Hi Droliven,

Thanks for your impressive work on human motion generation and the code contribution to the community. I just have a few concerns about the computation in MMADE and MMFDE, it seems that you use some of the code from gsps [Generating Smooth Pose Sequences for Diverse Human Motion Prediction](https://github.com/wei-mao-2019/gsps) in computing the evaluation metrics, however, what I do not understand is that in gsps for the computation of MMADE and MMFDE, they do not include the results from the ground truth [gsps#L230-L245](https://github.com/wei-mao-2019/gsps/blob/main/eval.py#L230-L245), while you did in your code [#L309-L343](https://github.com/Droliven/diverse_sampling/blob/main/h36m/runs/losses.py#L309-L343) and [#L320-L354](https://github.com/Droliven/diverse_sampling/blob/main/humaneva/runs/losses.py#L320-L354). Is there any special reason here? Thanks for your attention in advance.

Best,
Xiaoyu

**Comment by Droliven** [comment]
Sorry for the late reply,  you are very meticulous. But we are both right and the results obtained by these methods are the same, you could check it. The reason why we use `gt` is because our `gt_multi` does not contain the ground truth, but the `gt_multi` in GSPS does.

**Comment by Droliven** [comment]
By the way, one of the reviewer suggested we to add the ADE-m and FDE-m metrics which are supposed by you in "HiT-DVAE: Human Motion Generation via Hierarchical Transformer Dynamical VAE", during the rebuttal process. What a wonderful experience!
